apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cluster-ingress
  namespace: nextcloud
spec:
  rules:
  - host: files.mysite.test
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud-server
          servicePort: 80
