apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-claim
  labels:
    app: nextcloud
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
